### ISSUE TITLE
Sample Jupyter notebooks from each facility - Oct 2019

### ISSUE THREAD

**Issue by RobertRosca** [panosc-eu/wp4#1]
- [ ] Compile document of small use cases, safe to access by the public, which leads to a scientifically interesting result (figure, table, plot)
- [ ] Work closely with scientists to provide realistic and useful use cases
- [ ] Get sample data analysis use cases from each partner facility
- [ ] Provide a way for all partners to view and execute these
- [ ] Copy example data to STFC storage so all partners can access it easily
- [ ] Provision some compute resources for running the notebooks
- [ ] Identify areas where notebook ecosystem is lacking and cannot perform tasks required for the analysis

**Comment by RobertRosca** [comment]
I've done work on running Jupyter notebook kernels from inside Singularity containers, this could be used here to let us easily move compute environments between facilities.

**Comment by fangohr** [comment]
The STFC storage may not be accessible so easy, but we also have funds for cloud storage. And initially, we should just run these demos locally where the data is.

I think it is much more important to get something simple going soon, then something more sophisticated later.
